package aiml.aimlValidate;

import android.content.Context;
import android.util.Log;

import org.alicebot.ab.R;
import org.xml.sax.ErrorHandler;
import org.xml.sax.SAXException;
import org.xml.sax.SAXParseException;

import java.io.IOException;
import java.io.StringReader;

import mf.javax.xml.transform.Source;
import mf.javax.xml.transform.stream.StreamSource;
import mf.javax.xml.validation.Schema;
import mf.javax.xml.validation.Validator;
import mf.org.apache.xerces.jaxp.validation.XMLSchemaFactory;

/**
 * @author mukundan
 * Created by mukundan
 * A class to validate the AIML file with respect to the AIML 2.0 specification
 */
public class AIMLValidate {
    protected static final String TAG = "AIML VALIDATION";
    Validator validator;
    XMLSchemaFactory factory;
    Source schemaFile,xmlSource;
    Schema schema;
    Context context;


    /**
     * A contractor to initialize the object with the current context
     * @param context : The current context which is initializing the object for further use
     */
    public AIMLValidate(Context context){
        this.context = context;
    }

    /**
     * Function which validates the file against the schema in the raw folder
     * @param xmlDoc : Current XMLDOC as a string
     * @return True if file is valid AIML else false
     * @throws Error
     * @throws Exception
     */

    public boolean aimlValidate(String xmlDoc) throws Error, Exception {
        try {
            factory = new XMLSchemaFactory();
            schemaFile = new StreamSource(context.getResources().openRawResource(R.raw.aiml_schema));
            xmlSource = new StreamSource(new StringReader(xmlDoc));
            schema = factory.newSchema(schemaFile);
            validator = schema.newValidator();
            validator.setErrorHandler(new SimpleErrorHandler());
            validator.validate(xmlSource);

        } catch (SAXException e) {

            Log.e(TAG,"SAX EXCEPTION "+e.getMessage());
            throw e;
        } catch (IOException e) {
            Log.e(TAG,"IO EXCEPTION");
            throw e;
        } catch (Exception e) {
            e.printStackTrace();
            Log.e(TAG,"EXCEPTION");
            throw e;
        } catch (Error e) {
            e.printStackTrace();
            throw e;
        }

        return true;
    }
}

/**
 * A simple class to handle Errors generated by the validator
 */
class SimpleErrorHandler implements ErrorHandler{



    @Override
    public void error(SAXParseException arg0) throws SAXException {
        // TODO Auto-generated method stub
        Log.e(AIMLValidate.TAG,"Error " + arg0.getLineNumber() + " Message " + arg0.getMessage());
        throw arg0;
    }

    @Override
    public void fatalError(SAXParseException arg0) throws SAXException {
        // TODO Auto-generated method stub
        Log.e(AIMLValidate.TAG, "Fatal Error " + arg0.getLineNumber() + " Message " + arg0.getMessage());
        throw arg0;
    }

    @Override
    public void warning(SAXParseException arg0) throws SAXException {
        // TODO Auto-generated method stub
        Log.w(AIMLValidate.TAG,"Warning " + arg0.getLineNumber() + " Message " + arg0.getMessage());
        throw arg0;
    }

}
